//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaRamiros
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.VentaProducto = new HashSet<VentaProducto>();
        }
    
        public int Id_Prod { get; set; }
        public int Id_TipoProd { get; set; }
        public string Descripcion { get; set; }
        public int Id_TipoUnidad { get; set; }
        public decimal Disponible { get; set; }
        public Nullable<decimal> Valor_Unidad { get; set; }
    
        public virtual TipoProd TipoProd { get; set; }
        public virtual TipoUnidad TipoUnidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaProducto> VentaProducto { get; set; }
    }
}
